// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eMeni.Infrastructure.Models;

public sealed class StatisticEntity
{
    public int Id { get; set; }

    public int BusinessId { get; set; }

    public DateOnly? Date { get; set; }

    public int? ViewsCount { get; set; }

    public int? ReservationsCount { get; set; }

    public BusinessEntity Business { get; set; }
}