// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using eMeni.Domain.Common;
using System;
using System.Collections.Generic;

namespace eMeni.Infrastructure.Models;

public sealed class ReviewEntity:BaseEntity
{

    public int UserId { get; set; }

    public int BusinessId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public BusinessEntity Business { get; set; }

    public eMeniUserEntity User { get; set; }
}