// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using eMeni.Domain.Common;
using System;
using System.Collections.Generic;

namespace eMeni.Infrastructure.Models;

public sealed class BusinessesCategoryEntity : BaseEntity
{
    public string CategoryName { get; set; }

    public ICollection<BusinessEntity> Businesses { get; set; } = new List<BusinessEntity>();
}