// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eMeni.Infrastructure.Models.Configurations;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace eMeni.Infrastructure.Models;

public partial class eMeniContext : DbContext
{
    public eMeniContext(DbContextOptions<eMeniContext> options)
        : base(options)
    {
    }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.RefreshTokenEntityConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
