// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eMeni.Infrastructure.Models;

public partial class RefreshToken
{
    public int Id { get; set; }

    public string TokenHash { get; set; }

    public DateTime ExpiresAtUtc { get; set; }

    public bool IsRevoked { get; set; }

    public int UserId { get; set; }

    public string Fingerprint { get; set; }

    public DateTime? RevokedAtUtc { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? ModifiedAtUtc { get; set; }
}