// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using eMeni.Domain.Common;
using System;
using System.Collections.Generic;

namespace eMeni.Infrastructure.Models;

public sealed class OrderItemEntity:BaseEntity
{
    public int OrderId { get; set; }

    public int QRCodeProductId { get; set; }

    public short Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal? TotalPrice { get; set; }

    public string QRLink { get; set; }

    public string CustomText { get; set; }


    public OrderEntity Order { get; set; }

    public QRCodeProductEntity QRCodeProduct { get; set; }
}