// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using eMeni.Domain.Common;
using System;
using System.Collections.Generic;

namespace eMeni.Infrastructure.Models;

public sealed class OrderEntity:BaseEntity
{

    public int UserId { get; set; }

    public int BusinessId { get; set; }

    public DateTime? OrderDate { get; set; }

    public string Status { get; set; }

    public decimal? TotalAmount { get; set; }

    public string PaymentMethod { get; set; }

    public string Notes { get; set; }

    public string ShipAddress { get; set; }

    public BusinessEntity Business { get; set; }

    public ICollection<OrderItemEntity> OrderItems { get; set; } = new List<OrderItemEntity>();

    public ICollection<PaymentEntity> Payments { get; set; } = new List<PaymentEntity>();

    public eMeniUserEntity User { get; set; }
}