// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eMeni.Infrastructure.Models;

public sealed class PaymentEntity
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int? OrderId { get; set; }

    public decimal Amount { get; set; }

    public DateTime? PaymentDate { get; set; }

    public string PaymentMethod { get; set; }

    public string Status { get; set; }

    public string TransactionID { get; set; }

    public string Notes { get; set; }

    public OrderEntity Order { get; set; }

    public eMeniUserEntity User { get; set; }
}